# Generated by Django 4.1.4 on 2022-12-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_firstname_members_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
