# Generated by Django 4.1.4 on 2022-12-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(default='developer', max_length=255),
        ),
    ]
