# Generated by Django 4.1.4 on 2022-12-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(default='Developer', max_length=255),
        ),
    ]
